### PR TITLE
Add auth middleware for basic auth

### PR DESCRIPTION
**Pull request by sulochan**
- Adds paste based deploy
- Adds middleware for both simple and keystone based auth
- Few restructuring

### CODE REVIEW

**Comment by sulochan** [comment]
See Also: https://github.com/rackerlabs/craton/pull/29

**Comment by sulochan** [comment]
https://github.com/rackerlabs/craton/issues/30

**Comment by mwturvey** [comment]
+1-- looks good to me.

**Comment by jimbaker** [comment]
Follows our discussion to support basic auth as a minimum, looks good to me

**Pull request merged**
