### PR TITLE
Revert "Remove netaddr workaround now that oslo.serialization supports ipaddress"

### PR DESCRIPTION
**Pull request by sulochan**
Reverts rackerlabs/craton#95

### CODE REVIEW

**Comment by sulochan** [comment]
oslo.serialization 2.8.0 does not seem to have the required change to make the previous PR work.

Please double check before merging.

**Comment by sigmavirus24** [comment]
You're correct. https://github.com/openstack/oslo.serialization/releases/tag/2.8.0 shows that it is a parent of https://github.com/openstack/oslo.serialization/commit/0aa16384082a340fbcbe519255ed6dd83d8cad8d which means that @jimbaker's fix came after 2.8.0 was released. I suspect the next release (this week or next) will support not having to use netaddr.

**Comment by jimbaker** [comment]
Sounds good, let's keep this on hold. I will also add some sort of test to this branch -  we might as well know that hosts properly serialize with ip addresses.

**Comment by ChristopherMSpencer** [comment]
+1

**Comment by sulochan** [comment]
the latest release done today has the required code. closing this.

**Pull request closed without merging**
